### ISSUE TITLE
thoughts on other similar libraries....

### ISSUE THREAD

**Issue by sirvon** [eveoh/aspectj-example#1]
Thanks for your work...

There are similar plugins out there in the wild...

Just wanted your thoughts on the similarites, disadvatages, etc btw them all.

https://github.com/eveoh/gradle-aspectj
https://github.com/leolin310148/GradleAndroidAspectJPlugin
https://github.com/Archinamon/GradleAspectJ-Android

Thank You.

*I've raised the same issue with the other library authors.

**Comment by MikeN123** [comment]
I don't know the other libraries, and we're not actively using our library anymore, so can't really comment on that. The only thing I see is that the others seem to be Android specific, while ours has not even been tested with an Android build. That's about all I can say I guess.
