### ISSUE TITLE
Does not weave join points in test folder if the advice is defined in src/main

### ISSUE THREAD

**Issue by bharathcp** [eveoh/aspectj-example#2]
I am writing an @Around that is to be included as a jar in other projects. To test this aspect, i have written some test classes/methods which are eligible joint points for the advice defined in src folder.  
When I run my test cases, I get a warning saying the:
[ant:iajc] pathto/MyAdvice.java:24 [warning] advice defined in mypackage.MyAdvice has not been applied [Xlint:adviceDidNotMatch].
project
----|-- src
--------|-- main
------------|-- java
----------------|-- MyAdvice.java
----|-- test
--------|-- java
-------------|-- MyTest.java
-------------|-- MyJoinPoints.java
If the joint points are moved to main/java and called from test cases, then it works fine.
project
----|-- src
--------|-- main
------------|-- java
----------------|-- MyAdvice.java
----------------|-- MyJoinPoints.java
--------|-- test
------------|-- java
----------------|-- MyTest.java

It does not cosider joinPoints in test folders while weaving.

**Comment by MikeN123** [comment]
You would need to add the main aspects to your test build, something like:

```
dependencies {
    testAspectpath files("$buildDir/classes/main")
}
```

This project is not used by us anymore, so I can't really help you with this.
